export DATABASE_URL='postgres://postgres:0153@localhost:5432/capstone'
export EXCITED='true'
export FLASK_APP=app.py
export AUTHORIZATION_BEARER="Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNRbVBrVlU3dHRTa2NfVlptN0kyTyJ9.eyJpc3MiOiJodHRwczovL3N1cGVyYnVyZ2VyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZmY1M2U5Yjc4MjM4YjAwNzE5NzVhNDIiLCJhdWQiOiJzdXBlcmFwaSIsImlhdCI6MTYxMDEzODk4NywiZXhwIjoxNjEwMjI1Mzg3LCJhenAiOiJUOFBqVlluZmtlSzlUNDJtT3lFM0dLU21pNUF3N3BWRCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOm1lbnVfaXRlbSIsImdldDppdGVtX2RldGFpbHMiLCJnZXQ6bWVudV9pdGVtcyIsInBhdGNoOmNhdGVnb3J5IiwicG9zdDpjYXRlZ29yeSIsInBvc3Q6bWVudV9pdGVtIl19.m9Gvp9DQQ7KW5m_11xsAXlanqYLQs6ywSNpW4M28EpDTmMTvJIyhgEjeCWfWjzn_c3VQa50itl-iDtociMyU9ouoSCjDzgGV2bb-VhZoE0Oui-hv4diGhvEgA_wSfmjZQGw2oCRegDc8TJManCxpUywnHDUWnU20tCOHF0-zKSXrL4OJ59VVgADax9Xvy1uSnj4Cq_R_pVrva8Kb29qWXRFOiw3ExlfvMMPg2P7-InCTRD_jikWC1Ko_bJbMmBAxRTRDuPmBRjLWSvfGW7aotzewV_MFYfLZ6oxK68YO3bi7ISg4Lz8SCSSv52ca4olyw2XC0EJbedqTeWx9FjrdMQ"
export AUTH0_DOMAIN="superburger.us.auth0.com"
export API_AUDIENCE="superapi"
export LOGIN_URL="https://superburger.us.auth0.com/authorize?audience=superapi&response_type=token&client_id=T8PjVYnfkeK9T42mOyE3GKSmi5Aw7pVD&redirect_uri=https://superburger-suez.herokuapp.com/"
export LOGIN_LOCAL_URL="https://superburger.us.auth0.com/authorize?audience=superapi&response_type=token&client_id=T8PjVYnfkeK9T42mOyE3GKSmi5Aw7pVD&redirect_uri=https://localhost:5000"

